// Central UI resources. Keep printf placeholders and hidden ImGui IDs consistent.
YUVRAW_UI_TEXT(Language, u8"界面语言", "Language")
YUVRAW_UI_TEXT(LanguageChinese, u8"简体中文", u8"简体中文")
YUVRAW_UI_TEXT(LanguageEnglish, "English", "English")
YUVRAW_UI_TEXT(LanguageApplyHelp, u8"点击“应用”后生效，无需重启", "Takes effect on Apply; no restart required")
YUVRAW_UI_TEXT(LanguageSaveFailed, u8"语言保存失败，请检查设置目录是否可写", "Could not save language. Check settings folder permissions")
YUVRAW_UI_TEXT(SupportedImages, u8"支持的图像格式", "Supported images")
YUVRAW_UI_TEXT(AllFiles, u8"所有文件", "All files")
YUVRAW_UI_TEXT(Gray8Format, u8"灰度8", "Grayscale 8-bit")
YUVRAW_UI_TEXT(Gray16Format, u8"灰度16", "Grayscale 16-bit")
YUVRAW_UI_TEXT(RawBytesFormat, u8"RAW (原始字节)", "RAW (bytes)")
YUVRAW_UI_TEXT(Bayer10Format, u8"Bayer 10bit (16bit 容器)", "Bayer 10bit (16bit container)")
YUVRAW_UI_TEXT(Bayer12Format, u8"Bayer 12bit (16bit 容器)", "Bayer 12bit (16bit container)")
YUVRAW_UI_TEXT(Bayer14Format, u8"Bayer 14bit (16bit 容器)", "Bayer 14bit (16bit container)")
YUVRAW_UI_TEXT(DecodeFileFailed, u8"无法解码该文件", "Could not decode this file")
YUVRAW_UI_TEXT(IncompleteLoadParameters, u8"参数不完整：请先指定格式与分辨率", "Specify the format and dimensions first")
YUVRAW_UI_TEXT(LoadFileTooSmall, u8"按当前参数需要 %llu 字节，文件只有 %llu 字节", "Expected %llu bytes with these parameters; the file has only %llu bytes")
YUVRAW_UI_TEXT(DecodeParametersFailed, u8"按当前参数无法解码该文件", "Could not decode this file with the current parameters")
YUVRAW_UI_TEXT(FileNoLongerExists, u8"文件已不存在或不是普通文件", "File no longer exists or is not a regular file")
YUVRAW_UI_TEXT(BackgroundDecodeException, u8"后台解码发生异常", "Background decoding failed with an exception")
YUVRAW_UI_TEXT(BackgroundDecodeUnknownException, u8"后台解码发生未知异常", "Background decoding failed with an unknown exception")
YUVRAW_UI_TEXT(SynchronousDecodeException, u8"同步解码发生异常", "Synchronous decoding failed with an exception")
YUVRAW_UI_TEXT(TextureCreationFailed, u8"GPU 纹理创建失败", "Could not create GPU textures")
YUVRAW_UI_TEXT(InvalidLoadParameters, u8"格式、尺寸、行跨距或位深参数无效", "Invalid format, dimensions, stride or bit depth")
YUVRAW_UI_TEXT(ImageResourceLimit, u8"图像尺寸或解码缓冲超过安全上限", "Image dimensions or decode buffer exceed the supported limit")
YUVRAW_UI_TEXT(ImageFileAccess, u8"无法读取文件，请检查文件是否存在及访问权限", "Could not read the file; check its existence and permissions")
YUVRAW_UI_TEXT(ImageTruncated, u8"文件数据不完整，无法读取完整图像", "File is truncated; the complete image cannot be read")
YUVRAW_UI_TEXT(ImageDecodeFailure, u8"无法解码该文件，文件可能损坏或格式不受支持", "Could not decode the file; it may be corrupt or unsupported")
YUVRAW_UI_TEXT(ImageOutOfMemory, u8"内存不足，无法分配图像缓冲", "Not enough memory for the image buffer")
YUVRAW_UI_TEXT(ImageCodecUnavailable, u8"系统缺少此格式的 WIC 解码器", "No WIC decoder is installed for this format")
YUVRAW_UI_TEXT(CompareMissingImage, u8"有一幅图未加载", "One of the images is not loaded")
YUVRAW_UI_TEXT(CompareSizeMismatchPrefix, u8"分辨率不一致：", "Dimensions do not match: ")
YUVRAW_UI_TEXT(RgbConversionFailed, u8"转换到 RGB 失败", "Could not convert to RGB")
YUVRAW_UI_TEXT(ConvertedSizeMismatch, u8"转换结果大小不一致", "Converted image sizes do not match")
YUVRAW_UI_TEXT(WicFactoryFailed, u8"无法创建 WIC 工厂", "Could not create the WIC factory")
YUVRAW_UI_TEXT(CreateOutputFailed, u8"无法创建输出文件（目录不存在或没有写权限）", "Could not create output file; check the folder and write permissions")
YUVRAW_UI_TEXT(EncoderUnavailable, u8"系统缺少该格式的编码器", "No encoder is installed for this format")
YUVRAW_UI_TEXT(CreateOutputFrameFailed, u8"无法创建输出帧", "Could not create output frame")
YUVRAW_UI_TEXT(InitializeOutputFrameFailed, u8"初始化输出帧失败", "Could not initialize output frame")
YUVRAW_UI_TEXT(CreateSourceBitmapFailed, u8"无法建立源位图", "Could not create source bitmap")
YUVRAW_UI_TEXT(WriteOutputFailed, u8"写入文件失败", "Could not write the file")
YUVRAW_UI_TEXT(WriteOutputDiskFull, u8"写入文件失败（磁盘空间不足？）", "Could not write the file; the disk may be full")
YUVRAW_UI_TEXT(InvalidSourceImage, u8"源图像无效", "Invalid source image")
YUVRAW_UI_TEXT(UnsupportedRgbConversion, u8"该格式暂不支持转换为 RGB", "RGB conversion is not supported for this format")
YUVRAW_UI_TEXT(EmptyImageData, u8"图像数据为空", "Image data is empty")
YUVRAW_UI_TEXT(WebpDimensionLimit, u8"WebP 单边最大 16384 像素", "WebP dimensions cannot exceed 16384 pixels")
YUVRAW_UI_TEXT(ErrorSeparator, u8"：", ": ")
YUVRAW_UI_TEXT(Compare, u8"对比", u8"Compare")
YUVRAW_UI_TEXT(MainImage, u8"主图", u8"Main")
YUVRAW_UI_TEXT(RemoveMainImage, u8"移除主图", u8"Remove main image")
YUVRAW_UI_TEXT(NotLoaded, u8"未加载", u8"Not loaded")
YUVRAW_UI_TEXT(CompareImage, u8"对比图", u8"Comparison")
YUVRAW_UI_TEXT(RemoveCompareImage, u8"移除对比图", u8"Remove comparison image")
YUVRAW_UI_TEXT(ChooseCompareImageAction, u8"选择对比图...", u8"Choose comparison...")
YUVRAW_UI_TEXT(ChooseCompareImage, u8"选择对比图", u8"Choose comparison image")
YUVRAW_UI_TEXT(Difference, u8"差值", u8"Difference")
YUVRAW_UI_TEXT(DifferenceGain, u8"放大 %.0f 倍", u8"Gain %.0fx")
YUVRAW_UI_TEXT(ComputeDifference, u8"计算差值", u8"Compute difference")
YUVRAW_UI_TEXT(LoadBothImages, u8"需要同时加载主图和对比图", u8"Load both images to compare")
YUVRAW_UI_TEXT(MaximumDifference, u8"最大差异: %d / 255", u8"Max difference: %d / 255")
YUVRAW_UI_TEXT(MeanDifference, u8"平均差异: %.4f", u8"Mean difference: %.4f")
YUVRAW_UI_TEXT(DifferentPixels, u8"差异像素: %lld (%.4f%%)", u8"Different pixels: %lld (%.4f%%)")
YUVRAW_UI_TEXT(IdenticalPsnr, u8"PSNR: ∞ (完全一致)", u8"PSNR: inf (identical)")
YUVRAW_UI_TEXT(CompareMode, u8"对比模式", u8"Compare mode")
YUVRAW_UI_TEXT(SingleImageSwitch, u8"单图切换", u8"Switch")
YUVRAW_UI_TEXT(DifferenceImage, u8"差值图", u8"Difference image")
YUVRAW_UI_TEXT(TileImages, u8"平铺", u8"Tile")
YUVRAW_UI_TEXT(TileImagesHelp, u8"主图与对比图按工具栏选择左右或上下平铺。\n顶部链条按钮可切换拖动与缩放同步，默认开启；\n镜像、旋转等其它变换始终各自独立。", u8"Use the toolbar to tile images horizontally or vertically.\nThe link button synchronizes pan and zoom (enabled by default).\nMirroring, rotation and other transforms remain independent.")
YUVRAW_UI_TEXT(ExportImage, u8"导出图像", u8"Export images")
YUVRAW_UI_TEXT(NoExportSelection, u8"尚未选择要导出的图像", u8"No images selected for export")
YUVRAW_UI_TEXT(SelectedPrefix, u8"已选择 ", u8"Selected ")
YUVRAW_UI_TEXT(FilesSuffix, u8" 个文件", u8" files")
YUVRAW_UI_TEXT(NoSourceFile, u8"无源文件", u8"No source file")
YUVRAW_UI_TEXT(FirstImagePrefix, u8"  ·  首张 ", u8"  ·  First: ")
YUVRAW_UI_TEXT(OriginalSizePrefix, u8"原始尺寸  ", u8"Original size:  ")
YUVRAW_UI_TEXT(WaitingSourceInfo, u8"等待源图信息", u8"Waiting for source information")
YUVRAW_UI_TEXT(FileFormat, u8"文件格式", u8"File format")
YUVRAW_UI_TEXT(Format, u8"格式", u8"Format")
YUVRAW_UI_TEXT(WebpEncodingHelp, u8"无损 WebP。Windows 自带 WebP 解码器但不带编码器，\n这里用的是项目内置 VP8L 编码器，压缩率不及 PNG。", u8"Lossless WebP, using the built-in VP8L encoder.\nWindows provides a decoder only. Compression is less efficient than PNG.")
YUVRAW_UI_TEXT(EncodingQuality, u8"编码质量", u8"Quality")
YUVRAW_UI_TEXT(LosslessQualityHelp, u8"无损编码，无需设置质量", u8"Lossless encoding; no quality setting needed")
YUVRAW_UI_TEXT(Color, u8"色彩", u8"Color")
YUVRAW_UI_TEXT(ColorStandard, u8"色彩标准", u8"Color standard")
YUVRAW_UI_TEXT(ColorRange, u8"数值范围", u8"Range")
YUVRAW_UI_TEXT(NonYuvMatrixHelp, u8"源图不是 YUV，无需设置色彩矩阵", u8"No YUV matrix needed for this source")
YUVRAW_UI_TEXT(Clip, u8"裁剪", u8"Clip")
YUVRAW_UI_TEXT(ExportColorSummary, u8"跟随属性面板：原色 %s / 传输 %s / 色调映射 %s", u8"From Properties: primaries %s / transfer %s / tone mapping %s")
YUVRAW_UI_TEXT(OutputSize, u8"输出尺寸", u8"Output size")
YUVRAW_UI_TEXT(OriginalSize, u8"原始尺寸", u8"Original")
YUVRAW_UI_TEXT(ScaleByPercent, u8"按比例", u8"Scale")
YUVRAW_UI_TEXT(ScaleByWidth, u8"按宽度", u8"Width")
YUVRAW_UI_TEXT(ScaleFactor, u8"缩放比例", u8"Scale")
YUVRAW_UI_TEXT(TargetWidth, u8"目标宽度", u8"Target width")
YUVRAW_UI_TEXT(ExportAs, u8"导出为", u8"Output")
YUVRAW_UI_TEXT(FirstOutputDimensions, u8"%d × %d px（以首张为例）", u8"%d × %d px (first image)")
YUVRAW_UI_TEXT(WaitingSourceSize, u8"等待源图尺寸", u8"Waiting for source dimensions")
YUVRAW_UI_TEXT(AspectRatioHelp, u8"高度按原始宽高比自动推算，仅支持等比例缩放", u8"Height is calculated to preserve the original aspect ratio")
YUVRAW_UI_TEXT(SaveLocation, u8"保存位置", u8"Save location")
YUVRAW_UI_TEXT(ChooseDirectoryAction, u8"选择目录...", u8"Choose folder...")
YUVRAW_UI_TEXT(ChooseSaveDirectory, u8"选择保存目录", u8"Choose output folder")
YUVRAW_UI_TEXT(OverwriteFiles, u8"覆盖同名文件", u8"Overwrite existing files")
YUVRAW_UI_TEXT(OverwriteFilesHelp, u8"不勾选时遇到同名文件会自动添加 _1、_2 后缀", u8"When unchecked, duplicate names receive _1, _2 suffixes")
YUVRAW_UI_TEXT(SaveTo, u8"保存到", u8"Save to")
YUVRAW_UI_TEXT(SourceDirectory, u8"源文件所在目录", u8"Source file folder")
YUVRAW_UI_TEXT(ExportResults, u8"导出结果", u8"Export results")
YUVRAW_UI_TEXT(RevealExportHelp, u8"%s\n点击在资源管理器中定位该文件", u8"%s\nClick to show this file in Explorer")
YUVRAW_UI_TEXT(MoreResults, u8"…另有 %d 个", u8"...and %d more")
YUVRAW_UI_TEXT(BackgroundExportHelp, u8"导出在后台进行，处理期间界面会暂时置灰", u8"Export runs in the background; controls are temporarily disabled")
YUVRAW_UI_TEXT(Close, u8"关闭", u8"Close")
YUVRAW_UI_TEXT(StartExport, u8"开始导出", u8"Export")
YUVRAW_UI_TEXT(BrowseDirectory, u8"浏览文件夹...", u8"Browse folders...")
YUVRAW_UI_TEXT(OpenDirectory, u8"打开目录", u8"Open folder")
YUVRAW_UI_TEXT(CurrentDirectory, u8"当前目录", u8"Current folder")
YUVRAW_UI_TEXT(FileExplorer, u8"文件浏览器", u8"Files")
YUVRAW_UI_TEXT(Refresh, u8"刷新", u8"Refresh")
YUVRAW_UI_TEXT(ParentDirectory, u8"返回上级", u8"Up")
YUVRAW_UI_TEXT(Open, u8"打开", u8"Open")
YUVRAW_UI_TEXT(OpenInExplorer, u8"通过资源管理器打开", u8"Open in Explorer")
YUVRAW_UI_TEXT(AddComparison, u8"添加为对比图", u8"Add as comparison")
YUVRAW_UI_TEXT(Copy, u8"复制", u8"Copy")
YUVRAW_UI_TEXT(CopiedPrefix, u8"已复制 ", u8"Copied ")
YUVRAW_UI_TEXT(FileCopied, u8"已复制文件", u8"File copied")
YUVRAW_UI_TEXT(CopyFailed, u8"复制失败，请重试", u8"Copy failed. Please try again")
YUVRAW_UI_TEXT(CopyPath, u8"复制路径", u8"Copy path")
YUVRAW_UI_TEXT(FilePathsSuffix, u8" 个文件路径", u8" file paths")
YUVRAW_UI_TEXT(FilePathCopied, u8"已复制文件路径", u8"File path copied")
YUVRAW_UI_TEXT(CopyPathFailed, u8"复制路径失败，请重试", u8"Could not copy paths. Please try again")
YUVRAW_UI_TEXT(ExportSelectedPrefix, u8"导出选中的 ", u8"Export selected ")
YUVRAW_UI_TEXT(FilesActionSuffix, u8" 个文件...", u8" files...")
YUVRAW_UI_TEXT(ExportAction, u8"导出...", u8"Export...")
YUVRAW_UI_TEXT(MultiSelectHelp, u8"Shift/Ctrl + 左键可多选", u8"Shift/Ctrl + click to select multiple files")
YUVRAW_UI_TEXT(HistogramBin, u8"直方图档位: %d", u8"Histogram bin: %d")
YUVRAW_UI_TEXT(LumaValue, u8"亮度: %.0f", u8"Luma: %.0f")
YUVRAW_UI_TEXT(Histogram, u8"直方图", u8"Histogram")
YUVRAW_UI_TEXT(NoImageData, u8"无图像数据", u8"No image data")
YUVRAW_UI_TEXT(HistogramOverlay, u8"叠加显示", u8"Overlay")
YUVRAW_UI_TEXT(HistogramLogScale, u8"对数刻度", u8"Log scale")
YUVRAW_UI_TEXT(HistogramSampleCount, u8"采样 %lld 点（每 %d 像素取 1）", u8"%lld samples (1 per %d pixels)")
YUVRAW_UI_TEXT(HistogramFullCount, u8"全量统计 %lld 点", u8"All %lld pixels")
YUVRAW_UI_TEXT(Luma, u8"亮度", u8"Luma")
YUVRAW_UI_TEXT(SwitchImageHint, u8"点击左键切换对比图", u8"Left-click to switch images")
YUVRAW_UI_TEXT(CopiedCoordinates, u8"坐标\t(%d, %d)\r\n", u8"Coordinates\t(%d, %d)\r\n")
YUVRAW_UI_TEXT(CopiedSampleHeader, u8"分量\t主图\t对比图\t差值\r\n", u8"Channel\tMain\tComparison\tDifference\r\n")
YUVRAW_UI_TEXT(CopiedLuminance, u8"亮度\t%.1f cd/m2\r\n", u8"Luminance\t%.1f cd/m2\r\n")
YUVRAW_UI_TEXT(Loading, u8"正在加载...", u8"Loading...")
YUVRAW_UI_TEXT(ImageViewer, u8"图像查看器", u8"Image viewer")
YUVRAW_UI_TEXT(NoImageLoaded, u8"未加载图像", u8"No image loaded")
YUVRAW_UI_TEXT(FlipHorizontal, u8"水平镜像", u8"Flip horizontally")
YUVRAW_UI_TEXT(FlipVertical, u8"垂直镜像", u8"Flip vertically")
YUVRAW_UI_TEXT(RotateClockwise, u8"顺时针旋转 90°", u8"Rotate 90° clockwise")
YUVRAW_UI_TEXT(RotateCounterclockwise, u8"逆时针旋转 90°", u8"Rotate 90° counterclockwise")
YUVRAW_UI_TEXT(CopiedToClipboard, u8"已复制到剪切板", u8"Copied to clipboard")
YUVRAW_UI_TEXT(Coordinates, u8"坐标  (%d, %d)", u8"Coordinates  (%d, %d)")
YUVRAW_UI_TEXT(MainAndComparison, u8"主图 / 对比图", u8"Main / Comparison")
YUVRAW_UI_TEXT(Luminance, u8"亮度  %.1f cd/m²", u8"Luminance  %.1f cd/m²")
YUVRAW_UI_TEXT(CopySampleHelp, u8"右键复制所有信息", u8"Right-click to copy all values")
YUVRAW_UI_TEXT(AutoFit, u8"自适应", u8"Fit")
YUVRAW_UI_TEXT(Fill, u8"填充", u8"Fill")
YUVRAW_UI_TEXT(Reset, u8"重置", u8"Reset")
YUVRAW_UI_TEXT(ResetLinkedViewHelp, u8"重置当前图片的镜像与旋转，并同步重置两图的缩放与平移", u8"Reset this image's mirroring and rotation, and both images' pan and zoom")
YUVRAW_UI_TEXT(ResetViewHelp, u8"重置当前图片的镜像、缩放、旋转与平移", u8"Reset mirroring, zoom, rotation and pan for this image")
YUVRAW_UI_TEXT(Zoom, u8"缩放", u8"Zoom")
YUVRAW_UI_TEXT(ZoomHelp, u8"拖动调节，双击可直接输入。\n在画布上 Ctrl+滚轮则以鼠标位置为中心缩放。", u8"Drag to adjust; double-click to enter a value.\nCtrl + wheel on the canvas zooms around the pointer.")
YUVRAW_UI_TEXT(LinkedViewHelp, u8"同步拖动与缩放（已开启）\n镜像、旋转等其它变换仍各自独立。", u8"Pan and zoom are linked.\nMirroring, rotation and other transforms remain independent.")
YUVRAW_UI_TEXT(UnlinkedViewHelp, u8"同步拖动与缩放（已关闭）\n两张图的所有变换互不影响。", u8"Pan and zoom are unlinked.\nAll transforms are independent for each image.")
YUVRAW_UI_TEXT(TileHorizontalHelp, u8"水平并联（主图在左，对比图在右）", u8"Tile horizontally (main left, comparison right)")
YUVRAW_UI_TEXT(TileVerticalHelp, u8"垂直并联（主图在上，对比图在下）", u8"Tile vertically (main top, comparison bottom)")
YUVRAW_UI_TEXT(Settings, u8"设置", u8"Settings")
YUVRAW_UI_TEXT(File, u8"文件", u8"File")
YUVRAW_UI_TEXT(OpenFileAction, u8"打开文件...", u8"Open file...")
YUVRAW_UI_TEXT(OpenDirectoryAction, u8"打开目录...", u8"Open folder...")
YUVRAW_UI_TEXT(Exit, u8"退出", u8"Exit")
YUVRAW_UI_TEXT(Help, u8"帮助", u8"Help")
YUVRAW_UI_TEXT(About, u8"关于", u8"About")
YUVRAW_UI_TEXT(SaveFormatPresetPopup, u8"保存格式预设##ImageFormatPresetSavePopup", u8"Save format preset##ImageFormatPresetSavePopup")
YUVRAW_UI_TEXT(PresetNameEmpty, u8"名称不能为空", u8"Enter a name")
YUVRAW_UI_TEXT(PresetNameTooLong, u8"名称过长，请缩短后再保存", u8"Name is too long; please shorten it")
YUVRAW_UI_TEXT(PresetNameHashes, u8"名称不能包含连续的两个 # 字符", u8"Name cannot contain two consecutive # characters")
YUVRAW_UI_TEXT(PresetNameControls, u8"名称不能包含换行或控制字符", u8"Name cannot contain line breaks or control characters")
YUVRAW_UI_TEXT(PresetNameReserved, u8"名称不能与内建格式同名", u8"Name cannot match a built-in format")
YUVRAW_UI_TEXT(Properties, u8"属性面板", u8"Properties")
YUVRAW_UI_TEXT(SelfDescribingFormatHelp, u8"格式与尺寸由文件头决定，不可修改", u8"Format and dimensions are defined by the file header")
YUVRAW_UI_TEXT(EditingImage, u8"编辑对象", u8"Edit")
YUVRAW_UI_TEXT(EditingImageHelp, u8"选择本面板正在编辑哪一幅图。\n主图与对比图各自保留自己的格式/分辨率/stride 与色彩设置。", u8"Choose which image to edit.\nEach image keeps its own format, dimensions, stride and color settings.")
YUVRAW_UI_TEXT(ImageInfo, u8"图像信息", u8"Image information")
YUVRAW_UI_TEXT(ImageWidth, u8"宽度: %d", u8"Width: %d")
YUVRAW_UI_TEXT(ImageHeight, u8"高度: %d", u8"Height: %d")
YUVRAW_UI_TEXT(ImageStride, u8"Stride: %d 字节", u8"Stride: %d bytes")
YUVRAW_UI_TEXT(ImageBitsPerPixel, u8"每像素位数: %d", u8"Bits per pixel: %d")
YUVRAW_UI_TEXT(ImageChannels, u8"通道数: %d", u8"Channels: %d")
YUVRAW_UI_TEXT(ImageDataSize, u8"数据大小: %zu 字节", u8"Data size: %zu bytes")
YUVRAW_UI_TEXT(ImageFileSize, u8"文件大小: %llu 字节", u8"File size: %llu bytes")
YUVRAW_UI_TEXT(ExpectedFileSize, u8"按当前参数: %llu 字节", u8"Expected: %llu bytes")
YUVRAW_UI_TEXT(FileSizeMismatch, u8"与文件大小相差 %+lld 字节，格式/分辨率/stride 可能填错了", u8"Size differs by %+lld bytes; check format, dimensions and stride")
YUVRAW_UI_TEXT(FormatSelection, u8"格式选择", u8"Format selection")
YUVRAW_UI_TEXT(ImageFormat, u8"图像格式", u8"Image format")
YUVRAW_UI_TEXT(SaveFormatPresetAction, u8"保存##ImageFormatPreset", u8"Save##ImageFormatPreset")
YUVRAW_UI_TEXT(SaveFormatPresetHelp, u8"把当前格式、分辨率、stride 与采样布局保存为自定义预设", u8"Save the current format, dimensions, stride and sample layout as a preset")
YUVRAW_UI_TEXT(InvalidPresetParameters, u8"请先选择格式并填写有效分辨率", u8"Choose a format and enter valid dimensions first")
YUVRAW_UI_TEXT(PresetName, u8"预设名称", u8"Preset name")
YUVRAW_UI_TEXT(PresetParameters, u8"将保存当前完整加载参数：%s · %d × %d · stride %d", u8"Save all loading parameters: %s · %d × %d · stride %d")
YUVRAW_UI_TEXT(PresetSampleLayout, u8"位深 %d bit，并包含 Bayer 排布、字节序与有效位对齐设置", u8"%d-bit, including Bayer pattern, byte order and bit alignment")
YUVRAW_UI_TEXT(PresetOverwriteHelp, u8"同名预设将被覆盖，并移到下拉列表顶部", u8"A preset with this name will be replaced and moved to the top")
YUVRAW_UI_TEXT(Cancel, u8"取消", u8"Cancel")
YUVRAW_UI_TEXT(Overwrite, u8"覆盖", u8"Overwrite")
YUVRAW_UI_TEXT(Save, u8"保存", u8"Save")
YUVRAW_UI_TEXT(PresetUpdated, u8"格式预设已更新", u8"Format preset updated")
YUVRAW_UI_TEXT(PresetSaved, u8"格式预设已保存", u8"Format preset saved")
YUVRAW_UI_TEXT(PresetSaveFailed, u8"预设保存失败，请检查设置目录是否可写", u8"Could not save preset. Check settings folder permissions")
YUVRAW_UI_TEXT(Resolution, u8"分辨率", u8"Resolution")
YUVRAW_UI_TEXT(NoMatch, u8"无匹配", u8"No match")
YUVRAW_UI_TEXT(ResolutionCandidates, u8"%d 种可能", u8"%d candidates")
YUVRAW_UI_TEXT(MismatchedCandidates, u8"对不上 · %d 种", u8"Mismatch · %d")
YUVRAW_UI_TEXT(CandidateWidthSample, u8"对不上 · 88 种", u8"Mismatch · 88")
YUVRAW_UI_TEXT(ResolutionCandidatesHelp, u8"由文件大小与当前格式反推可能的分辨率。\n文件名里解析到的分辨率也列在其中，但同样会被校验。", u8"Estimate dimensions from file size and format.\nDimensions parsed from the file name are also listed and validated.")
YUVRAW_UI_TEXT(FromFileName, u8"来自文件名", u8"From file name")
YUVRAW_UI_TEXT(ExactFileSize, u8"正好装满文件", u8"Exact fit")
YUVRAW_UI_TEXT(SizeMismatch, u8"对不上", u8"Mismatch")
YUVRAW_UI_TEXT(NoMatchingResolution, u8"该格式下没有正好装满文件的分辨率", u8"No resolution matches the file size for this format")
YUVRAW_UI_TEXT(MatchingFormats, u8"换成这些格式反而正好装满：", u8"These formats match the file size:")
YUVRAW_UI_TEXT(PackedFileSize, u8"按 %s 紧凑排列计算，文件 %llu 字节", u8"Packed %s layout; file size %llu bytes")
YUVRAW_UI_TEXT(AmbiguousStrideHelp, u8"带 padding 的排布字节数与紧凑排布相同，无法区分：\n若图像右侧出现绿色竖条，把宽度调小、stride 保持不变", u8"Padded and packed layouts have the same byte count.\nIf a green strip appears on the right, reduce width and keep stride unchanged.")
YUVRAW_UI_TEXT(BytesPerRow, u8"字节/行", u8"bytes/row")
YUVRAW_UI_TEXT(StrideHelp, u8"第 0 平面每行的字节数，含行尾 padding。\n默认是按当前格式与宽度紧凑排列的字节数。\n相机 dump 的 YUV 常按 16/32/64 字节对齐，\n例如 1440 宽的 NV21 实际 stride 可能是 1472。\n图像右侧出现绿色竖条通常就是没填对 stride。", u8"Bytes per row in plane 0, including padding.\nDefaults to the packed row size for this format and width.\nCamera YUV dumps often align to 16/32/64 bytes.\nFor example, 1440-wide NV21 may have a stride of 1472.\nA green strip on the right usually indicates an incorrect stride.")
YUVRAW_UI_TEXT(BayerPattern, u8"Bayer 排布", u8"Bayer pattern")
YUVRAW_UI_TEXT(BayerPatternHelp, u8"左上角 2x2 的滤色片排列。\n选错时整幅图颜色会明显翻车（红绿互换等）。", u8"Color filter arrangement in the top-left 2x2 block.\nAn incorrect pattern causes strong color shifts, such as swapped red and green.")
YUVRAW_UI_TEXT(BitDepth, u8"位深", u8"Bit depth")
YUVRAW_UI_TEXT(BitsPerPixel, u8"每像素位数", u8"Bits per pixel")
YUVRAW_UI_TEXT(FixedByFormat, u8"(格式固定)", u8"(fixed by format)")
YUVRAW_UI_TEXT(DisplaySettings, u8"显示设置", u8"Display settings")
YUVRAW_UI_TEXT(NoImageDataHint, u8"(无图像数据)", u8"(no image data)")
YUVRAW_UI_TEXT(YuvMatrix, u8"YUV 矩阵", u8"YUV matrix")
YUVRAW_UI_TEXT(YuvMatrixHelp, u8"选择源素材使用的 YCbCr -> RGB 转换矩阵。\n选错可能导致颜色偏差；源原色与传输函数需在下方分别设置。", u8"Select the source YCbCr to RGB conversion matrix.\nAn incorrect matrix shifts colors. Set primaries and transfer function separately below.")
YUVRAW_UI_TEXT(ColorRangeHelp, u8"按源素材的量化范围解读 YUV 码值。\n8 位：Limited 为 Y 16-235、U/V 16-240；Full 为 0-255。\n10 位：Limited 为 Y 64-940、U/V 64-960；Full 为 0-1023。\n选错可能导致黑位发灰，或暗部与高光细节丢失。", u8"Interpret YUV code values using the source quantization range.\n8-bit: Limited Y 16-235, U/V 16-240; Full 0-255.\n10-bit: Limited Y 64-940, U/V 64-960; Full 0-1023.\nAn incorrect range can raise blacks or lose shadow and highlight detail.")
YUVRAW_UI_TEXT(FullColor, u8"彩色", u8"Color")
YUVRAW_UI_TEXT(DisplayChannel, u8"显示通道", u8"Channel")
YUVRAW_UI_TEXT(YuvChannelHelp, u8"彩色：将 YUV 转为 RGB，并应用下方色彩设置。\nY/U/V：以灰度查看所选分量，不应用下方色彩设置。\nY 按所选数值范围拉伸；U/V 按原始码值显示。", u8"Color: convert YUV to RGB and apply the color settings below.\nY/U/V: show the selected component as grayscale, without those settings.\nY uses the selected range; U/V show raw code values.")
YUVRAW_UI_TEXT(BayerChannelHelp, u8"R/G/B：以灰度查看 Bayer 插值后的对应分量。\nBayer 没有透明度通道，选择 A 时仍显示彩色图像。", u8"R/G/B: show the interpolated Bayer component as grayscale.\nBayer has no alpha channel; A still displays the color image.")
YUVRAW_UI_TEXT(GrayscaleChannelHelp, u8"灰度格式始终显示单通道图像，此选项不改变画面。\n下方色彩设置仍然生效。", u8"Grayscale formats always show one channel; this choice has no effect.\nThe color settings below still apply.")
YUVRAW_UI_TEXT(RgbChannelHelp, u8"彩色：显示 RGB，并应用下方色彩设置。\nR/G/B/A：以灰度查看所选分量，不应用下方色彩设置。\nA 表示透明度；没有透明度通道时显示白色。", u8"Color: display RGB and apply the color settings below.\nR/G/B/A: show one component as grayscale, without those settings.\nA is alpha; images without alpha display white.")
YUVRAW_UI_TEXT(HdrTransfer, u8"HDR / 传输函数", u8"HDR / Transfer")
YUVRAW_UI_TEXT(SourcePrimaries, u8"源原色", u8"Primaries")
YUVRAW_UI_TEXT(SourcePrimariesHelp, u8"选择源素材的 RGB 三原色，决定其色域含义。\n程序据此转换到输出所用的 RGB 色彩空间。\n请按素材信息选择；此项不会自动修改 YUV 矩阵或传输函数。", u8"Select the source RGB primaries to define its color space.\nThe image is converted from these primaries to the output color space.\nUse the source specification; YUV matrix and transfer function remain unchanged.")
YUVRAW_UI_TEXT(Linear, u8"线性", u8"Linear")
YUVRAW_UI_TEXT(TransferFunction, u8"传输函数", u8"Transfer")
YUVRAW_UI_TEXT(TransferFunctionHelp, u8"选择源素材的码值到线性光的转换方式。\nSDR 按 sRGB 解读；BT.1886 使用 gamma 2.4；线性表示码值已是线性光。\nPQ 按绝对亮度解读；HLG 还需结合下方 HLG 峰值。\n请按素材信息选择，P010 等像素格式本身不能确定传输函数。", u8"Select how source code values convert to linear light.\nSDR uses sRGB; BT.1886 uses gamma 2.4; Linear means values are already linear.\nPQ specifies absolute luminance; HLG also uses the peak setting below.\nUse the source specification. A pixel format such as P010 cannot determine this.")
YUVRAW_UI_TEXT(ReferenceWhite, u8"参考白 (nit)", u8"Ref. white (nit)")
YUVRAW_UI_TEXT(ReferenceWhiteHelp, u8"PQ/HLG 转为 SDR 显示时，将此亮度归一化为线性值 1.0，再做色调映射。\n默认 203 nit；调大使画面变暗，调小使画面变亮。1 nit = 1 cd/m²。\nHDR 输出生效时不使用此项；SDR、BT.1886、线性输入下不可调整。", u8"For PQ/HLG to SDR, this luminance becomes linear 1.0 before tone mapping.\nDefault: 203 nit. Higher values darken the image; lower values brighten it.\n1 nit = 1 cd/m². Not used for HDR output or SDR, BT.1886 and Linear input.")
YUVRAW_UI_TEXT(HlgPeak, u8"HLG 峰值 (nit)", u8"HLG peak (nit)")
YUVRAW_UI_TEXT(HlgPeakHelp, u8"将 HLG 信号转换为显示亮度时采用的标称峰值，默认 1000 nit。\n它同时影响亮度尺度与系统 gamma，因此会改变画面的亮度和对比度。\n此值需手动指定，不会自动跟随当前显示器峰值。", u8"Nominal peak used to convert HLG to display luminance; default 1000 nit.\nIt affects both luminance scale and system gamma, changing brightness and contrast.\nSet it manually; it does not follow the current display peak.")
YUVRAW_UI_TEXT(ToneMapping, u8"色调映射", u8"Tone mapping")
YUVRAW_UI_TEXT(ToneMappingHelp, u8"选择 SDR 输出时的亮度映射方式，非 SDR 传输函数下可调整。\n裁剪：直接截断超出范围的值；Reinhard：压缩高光，可调映射白点；\nACES：使用电影风格的近似曲线压缩亮度。\nHDR 输出生效时不使用此项，而是按显示器峰值限制高光。", u8"Luminance mapping for SDR output; adjustable for non-SDR transfer functions.\nClip truncates values; Reinhard compresses highlights with an adjustable white point.\nACES uses a film-like approximation curve.\nHDR output instead limits highlights to the display peak.")
YUVRAW_UI_TEXT(MappingWhite, u8"映射白点", u8"White point")
YUVRAW_UI_TEXT(MappingWhiteHelp, u8"Reinhard 曲线中映射到输出白色（1.0）的线性输入值。\nPQ/HLG 转 SDR 时以参考白为单位，并在曝光调整后计算。\n数值越大，高光压缩越强；仅用于 SDR 输出的 Reinhard 映射。", u8"Linear input mapped to output white (1.0) by the Reinhard curve.\nFor PQ/HLG to SDR, measured in reference-white units after exposure adjustment.\nHigher values compress highlights more. Only used by Reinhard for SDR output.")
YUVRAW_UI_TEXT(Exposure, u8"曝光 (档)", u8"Exposure (EV)")
YUVRAW_UI_TEXT(ExposureHelp, u8"在色调映射或高光限幅前调整线性亮度。\n+1 档为原来的 2 倍，-1 档为原来的 1/2；0 档不调整。\nSDR 与 HDR 输出均适用。", u8"Adjust linear luminance before tone mapping or highlight limiting.\n+1 EV doubles luminance; -1 EV halves it; 0 leaves it unchanged.\nApplies to both SDR and HDR output.")
YUVRAW_UI_TEXT(HighlightOutOfRange, u8"超范围高亮", u8"Highlight out of range")
YUVRAW_UI_TEXT(HighlightOutOfRangeHelp, u8"在色调映射与裁剪前，用颜色标记超范围的 RGB 分量。\n红色：任一分量超过当前输出路径的上限。\n蓝色：任一分量为负，可能来自超黑或原色转换；红色优先。\n负分量不一定超出实际显示器色域，HDR 输出可保留负值。", u8"Mark out-of-range RGB values before tone mapping and clipping.\nRed: any component exceeds the output limit.\nBlue: any component is negative, from super-black or primary conversion; red wins.\nNegative values need not be outside the display gamut; HDR can preserve them.")
YUVRAW_UI_TEXT(HdrOutput, u8"HDR 输出", u8"HDR output")
YUVRAW_UI_TEXT(HdrOutputHelp, u8"为主窗口启用 HDR 输出，主图与对比图共用此开关。\nPQ/HLG 按解读后的亮度输出，仍受曝光与显示器峰值限制。\n关闭后按 SDR 显示；拖出主窗口的图像面板始终按 SDR 显示。", u8"Enable HDR output for the main window, including both images.\nPQ/HLG use interpreted luminance, subject to exposure and display peak limits.\nWhen disabled, output is SDR. Detached image windows always use SDR.")
YUVRAW_UI_TEXT(HdrUnavailableHelp, u8"%s\n\nHDR 输出需要显示器开启 HDR，且程序的 HDR 通路可用。\n若当前显示器未开启 HDR，可在系统设置中开启，或将主窗口移到已开启 HDR 的显示器。", u8"%s\n\nHDR requires an HDR-enabled display and a working HDR output path.\nEnable HDR in Windows or move the main window to an HDR-enabled display.")
YUVRAW_UI_TEXT(HdrEnabled, u8"已启用 (scRGB fp16)", u8"Enabled (scRGB fp16)")
YUVRAW_UI_TEXT(HdrDisplayInfo, u8"%s  峰值 %.0f nit  SDR 白 %.0f nit", u8"%s  Peak %.0f nit  SDR white %.0f nit")
YUVRAW_UI_TEXT(HdrLuminanceHelp, u8"PQ/HLG 不按参考白折算；曝光与峰值限幅仍生效", u8"PQ/HLG use absolute luminance; exposure and peak limiting still apply")
YUVRAW_UI_TEXT(HdrDisabled, u8"已关闭（按 SDR 显示）", u8"Disabled (SDR output)")
YUVRAW_UI_TEXT(Unavailable, u8"不可用", u8"Unavailable")
YUVRAW_UI_TEXT(ByteOrderNotApplicable, u8"该格式不使用多字节采样，字节序不适用。", u8"This format has no multi-byte samples; byte order does not apply.")
YUVRAW_UI_TEXT(FixedLittleEndian, u8"该格式固定为小端（低字节在前）。", u8"This format is always little-endian (low byte first).")
YUVRAW_UI_TEXT(FixedBigEndian, u8"该格式固定为大端（高字节在前）。", u8"This format is always big-endian (high byte first).")
YUVRAW_UI_TEXT(ByteOrder, u8"字节序", u8"Byte order")
YUVRAW_UI_TEXT(LittleEndian, u8"小端##ByteOrderLittle", u8"Little##ByteOrderLittle")
YUVRAW_UI_TEXT(LittleEndianHelp, u8"低字节在文件中位于高字节之前。", u8"The low byte precedes the high byte in the file.")
YUVRAW_UI_TEXT(BigEndian, u8"大端##ByteOrderBig", u8"Big##ByteOrderBig")
YUVRAW_UI_TEXT(BigEndianHelp, u8"高字节在文件中位于低字节之前。", u8"The high byte precedes the low byte in the file.")
YUVRAW_UI_TEXT(AlignmentNotApplicable, u8"该格式没有可选择的有效位对齐方式。", u8"This format has no selectable bit alignment.")
YUVRAW_UI_TEXT(FullContainerAlignment, u8"有效位已占满采样容器，高低位对齐结果相同；降低位深后可选择。", u8"All container bits are used, so both alignments are identical. Reduce bit depth to choose.")
YUVRAW_UI_TEXT(FixedLowAlignment, u8"该格式固定为低位对齐。", u8"This format is always aligned to the least significant bits.")
YUVRAW_UI_TEXT(FixedHighAlignment, u8"该格式固定为高位对齐。", u8"This format is always aligned to the most significant bits.")
YUVRAW_UI_TEXT(BitAlignment, u8"有效位对齐", u8"Bit alignment")
YUVRAW_UI_TEXT(LowAlignment, u8"低位##SampleAlignmentLow", u8"LSB##SampleAlignmentLow")
YUVRAW_UI_TEXT(LowAlignmentHelp, u8"有效位从采样容器的最低位开始存放。", u8"Valid bits start at the least significant bit of the sample container.")
YUVRAW_UI_TEXT(HighAlignment, u8"高位##SampleAlignmentHigh", u8"MSB##SampleAlignmentHigh")
YUVRAW_UI_TEXT(HighAlignmentHelp, u8"有效位贴齐采样容器的最高位存放。", u8"Valid bits end at the most significant bit of the sample container.")
YUVRAW_UI_TEXT(AboutPopup, u8"关于 YUVRaw", u8"About YUVRaw")
YUVRAW_UI_TEXT(ThirdPartyPopup, u8"第三方开源许可", u8"Third-party licenses")
YUVRAW_UI_TEXT(SettingsPopup, u8"设置##YUVRawSettingsPopup", u8"Settings##YUVRawSettingsPopup")
YUVRAW_UI_TEXT(ThemeAccent, u8"高亮色", u8"Accent")
YUVRAW_UI_TEXT(ThemeBackground, u8"界面背景", u8"Background")
YUVRAW_UI_TEXT(ThemeText, u8"文字", u8"Text")
YUVRAW_UI_TEXT(ThemeBorder, u8"边框", u8"Border")
YUVRAW_UI_TEXT(ThemeInput, u8"输入控件背景", u8"Input fields")
YUVRAW_UI_TEXT(ThemeControls, u8"按钮与选择色", u8"Controls")
YUVRAW_UI_TEXT(ThirdPartyIntro, u8"以下为 YUVRaw 使用的第三方开源软件及其许可文本。", u8"Third-party open-source software used by YUVRaw and its license texts.")
YUVRAW_UI_TEXT(OpenImage, u8"打开图像", u8"Open image")
YUVRAW_UI_TEXT(LoadingMain, u8"正在加载主图...", u8"Loading main image...")
YUVRAW_UI_TEXT(LoadingComparison, u8"正在加载对比图...", u8"Loading comparison image...")
YUVRAW_UI_TEXT(MainLoadFailedPrefix, u8"主图加载失败：", u8"Could not load main image: ")
YUVRAW_UI_TEXT(CompareLoadFailedPrefix, u8"对比图加载失败：", u8"Could not load comparison image: ")
YUVRAW_UI_TEXT(UnknownError, u8"未知错误", u8"Unknown error")
YUVRAW_UI_TEXT(ComputingDifference, u8"正在计算差值...", u8"Computing difference...")
YUVRAW_UI_TEXT(DifferenceFailed, u8"计算差值失败（内存不足？）", u8"Could not compute difference (out of memory?)")
YUVRAW_UI_TEXT(GeneratedDifferenceName, u8"<差值图>", u8"<Difference image>")
YUVRAW_UI_TEXT(WaitBeforeExport, u8"图片加载完成后再导出", u8"Wait for the image to finish loading before exporting")
YUVRAW_UI_TEXT(ExportInternalError, u8"导出失败：内部错误", u8"Export failed: internal error")
YUVRAW_UI_TEXT(ExportOutputPathUnavailable, u8"无法分配输出文件名，请检查目录权限或更换输出目录", u8"Could not allocate an output filename. Check directory permissions or choose another output directory.")
YUVRAW_UI_TEXT(Exporting, u8"正在导出...", u8"Exporting...")
YUVRAW_UI_TEXT(FileLoadFailedSuffix, u8"：无法加载（格式或分辨率参数不对？）", u8": could not load (check format and dimensions)")
YUVRAW_UI_TEXT(ExportComplete, u8"导出完成", u8"Export complete")
YUVRAW_UI_TEXT(ExportedPrefix, u8"已导出 ", u8"Exported ")
YUVRAW_UI_TEXT(SucceededPrefix, u8"成功 ", u8"Succeeded: ")
YUVRAW_UI_TEXT(FailedCountPrefix, u8" 个，失败 ", u8"; failed: ")
YUVRAW_UI_TEXT(SentenceEnd, u8" 个。", u8". ")
YUVRAW_UI_TEXT(ExportFailedPrefix, u8"导出失败：", u8"Export failed: ")
YUVRAW_UI_TEXT(RecentFiles, u8"最近打开", u8"Recent files")
YUVRAW_UI_TEXT(Empty, u8"(空)", u8"(empty)")
YUVRAW_UI_TEXT(ClearRecentFiles, u8"清空列表", u8"Clear list")
YUVRAW_UI_TEXT(ThemeColors, u8"主题颜色", u8"Theme colors")
YUVRAW_UI_TEXT(ImageCacheCapacity, u8"图片属性缓存数量", u8"Image cache capacity")
YUVRAW_UI_TEXT(ImagesUnit, u8"张", u8"images")
YUVRAW_UI_TEXT(ImageCacheSummary, u8"0 表示禁用，最多 %llu 张；当前已缓存 %llu 张", u8"0 disables caching. Limit: %llu; cached: %llu")
YUVRAW_UI_TEXT(CacheCapacityClamped, u8"应用时会自动限制到有效范围", u8"The value will be clamped to the valid range on Apply")
YUVRAW_UI_TEXT(ClearData, u8"清除数据", u8"Clear data")
YUVRAW_UI_TEXT(ClearImageCacheOnly, u8"仅清除图片属性缓存", u8"Only clear image cache")
YUVRAW_UI_TEXT(Apply, u8"应用", u8"Apply")
YUVRAW_UI_TEXT(SettingsSaved, u8"设置已保存", u8"Settings saved")
YUVRAW_UI_TEXT(SettingsCacheSaveFailed, u8"设置已保存，但缓存文件写入失败", u8"Settings saved, but the cache file could not be written")
YUVRAW_UI_TEXT(CacheClearSaveFailed, u8"缓存已清除，但持久化文件保存失败", u8"Cache cleared, but the cache file could not be saved")
YUVRAW_UI_TEXT(ClearedPrefix, u8"已清除 ", u8"Cleared cached settings for ")
YUVRAW_UI_TEXT(CachedImagesSuffix, u8" 张图片的缓存配置", u8" images")
YUVRAW_UI_TEXT(ImageCacheEmpty, u8"图片属性缓存已为空", u8"Image cache is already empty")
YUVRAW_UI_TEXT(AllDataCleared, u8"已清除所有缓存和数据，设置已恢复默认值", u8"All data cleared; settings restored to defaults")
YUVRAW_UI_TEXT(DataClearFailed, u8"部分数据清除失败，请查看日志", u8"Some data could not be cleared. Check the log")
YUVRAW_UI_TEXT(AppDescription, u8"图像查看、分析与对比工具", u8"View, analyze and compare images")
YUVRAW_UI_TEXT(AppVersion, u8"版本  %s", u8"Version  %s")
YUVRAW_UI_TEXT(OpenSourceNotice, u8"本软件使用开源组件构建。相关版权信息及完整许可文本，可通过下方“第三方许可”查看。", u8"This application uses open-source components. Copyright notices and full license texts are available under \"Third-party licenses\" below.")
YUVRAW_UI_TEXT(ThirdPartyLicenses, u8"第三方许可", u8"Third-party licenses")
YUVRAW_UI_TEXT(Confirm, u8"确定", u8"OK")
YUVRAW_UI_TEXT(NotInitialized, u8"未初始化", u8"Not initialized")
YUVRAW_UI_TEXT(HdrInvalidWindow, u8"HDR 不可用：窗口句柄无效", u8"HDR unavailable: invalid window handle")
YUVRAW_UI_TEXT(HdrInteropUnsupported, u8"HDR 不可用：驱动不支持 WGL_NV_DX_interop2", u8"HDR unavailable: driver does not support WGL_NV_DX_interop2")
YUVRAW_UI_TEXT(HdrDeviceFailed, u8"HDR 不可用：创建 D3D11 设备失败", u8"HDR unavailable: could not create D3D11 device")
YUVRAW_UI_TEXT(HdrFactoryFailed, u8"HDR 不可用：取 DXGI 工厂失败", u8"HDR unavailable: could not obtain DXGI factory")
YUVRAW_UI_TEXT(HdrSwapchainFailed, u8"HDR 不可用：创建交换链失败", u8"HDR unavailable: could not create swap chain")
YUVRAW_UI_TEXT(HdrSwapchainUnsupported, u8"HDR 不可用：IDXGISwapChain3 不可用", u8"HDR unavailable: IDXGISwapChain3 is not supported")
YUVRAW_UI_TEXT(HdrScRgbUnsupported, u8"HDR 不可用：交换链不支持 scRGB", u8"HDR unavailable: swap chain does not support scRGB")
YUVRAW_UI_TEXT(HdrColorSpaceFailed, u8"HDR 不可用：SetColorSpace1 失败", u8"HDR unavailable: SetColorSpace1 failed")
YUVRAW_UI_TEXT(HdrInteropFailed, u8"HDR 不可用：wglDXOpenDeviceNV 失败", u8"HDR unavailable: wglDXOpenDeviceNV failed")
YUVRAW_UI_TEXT(HdrGpuMismatch, u8"wglDXOpenDeviceNV failed (GL 与 D3D 可能不在同一块 GPU 上)", u8"wglDXOpenDeviceNV failed (GL and D3D may be on different GPUs)")
YUVRAW_UI_TEXT(HdrShaderFailed, u8"HDR 不可用：合成着色器编译失败", u8"HDR unavailable: compositor shader compilation failed")
YUVRAW_UI_TEXT(HdrReady, u8"HDR 通路就绪", u8"HDR output ready")
YUVRAW_UI_TEXT(HdrDisplayDisabled, u8"HDR 通路就绪（当前显示器未开启 HDR）", u8"HDR output ready (HDR is disabled on this display)")
YUVRAW_UI_TEXT(HdrFramebufferFailed, u8"HDR 已关闭：帧缓冲创建失败", u8"HDR disabled: framebuffer creation failed")
YUVRAW_UI_TEXT(HdrPresentFailed, u8"HDR 已关闭：呈现失败", u8"HDR disabled: presentation failed")
